const data = [
  {
      "id": 1,
      "accomodation_id": 1,
      "name": "部屋名A",
      "room_cd": "909090",
      "description": "この部屋の説明が入る",
      "count": 4,
      "capacity": 490,
      "weekday_price": 1000,
      "friday_price": 4000,
      "staurday_price": 2030,
      "before_holiday_price": 996,
      "deleted_at": null,
      "Accomodation": {
          "id": 0,
          "name": "",
          "description": "",
          "address": "",
          "phone_number": "",
          "site_url": "",
          "site_description": null,
          "questions": null,
          "deleted_at": null,
          "Rooms": null,
          "AccomodationDesigns": null,
          "Plans": null,
          "Options": null,
          "EmailSettings": null,
          "CancelPolicies": null,
          "AdminUsers": null,
          "TravelerTypes": null,
          "Reservations": null
      },
      "Plans": null,
      "RoomDetails": [
          {
              "id": 1,
              "room_id": 1,
              "stock": 10,
              "price": 1000,
              "date": "2021-10-10T00:00:00+09:00",
              "deleted_at": null,
              "Room": {
                  "id": 0,
                  "accomodation_id": 0,
                  "name": "",
                  "room_cd": "",
                  "description": "",
                  "count": 0,
                  "capacity": 0,
                  "weekday_price": 0,
                  "friday_price": 0,
                  "staurday_price": 0,
                  "before_holiday_price": 0,
                  "deleted_at": null,
                  "Accomodation": {
                      "id": 0,
                      "name": "",
                      "description": "",
                      "address": "",
                      "phone_number": "",
                      "site_url": "",
                      "site_description": null,
                      "questions": null,
                      "deleted_at": null,
                      "Rooms": null,
                      "AccomodationDesigns": null,
                      "Plans": null,
                      "Options": null,
                      "EmailSettings": null,
                      "CancelPolicies": null,
                      "AdminUsers": null,
                      "TravelerTypes": null,
                      "Reservations": null
                  },
                  "Plans": null,
                  "RoomDetails": null
              }
          },
          {
              "id": 2,
              "room_id": 1,
              "stock": 11,
              "price": 1000,
              "date": "2021-10-11T00:00:00+09:00",
              "deleted_at": null,
              "Room": {
                  "id": 0,
                  "accomodation_id": 0,
                  "name": "",
                  "room_cd": "",
                  "description": "",
                  "count": 0,
                  "capacity": 0,
                  "weekday_price": 0,
                  "friday_price": 0,
                  "staurday_price": 0,
                  "before_holiday_price": 0,
                  "deleted_at": null,
                  "Accomodation": {
                      "id": 0,
                      "name": "",
                      "description": "",
                      "address": "",
                      "phone_number": "",
                      "site_url": "",
                      "site_description": null,
                      "questions": null,
                      "deleted_at": null,
                      "Rooms": null,
                      "AccomodationDesigns": null,
                      "Plans": null,
                      "Options": null,
                      "EmailSettings": null,
                      "CancelPolicies": null,
                      "AdminUsers": null,
                      "TravelerTypes": null,
                      "Reservations": null
                  },
                  "Plans": null,
                  "RoomDetails": null
              }
          },
          {
              "id": 4,
              "room_id": 1,
              "stock": 0,
              "price": 1000,
              "date": "2021-10-13T00:00:00+09:00",
              "deleted_at": null,
              "Room": {
                  "id": 0,
                  "accomodation_id": 0,
                  "name": "",
                  "room_cd": "",
                  "description": "",
                  "count": 0,
                  "capacity": 0,
                  "weekday_price": 0,
                  "friday_price": 0,
                  "staurday_price": 0,
                  "before_holiday_price": 0,
                  "deleted_at": null,
                  "Accomodation": {
                      "id": 0,
                      "name": "",
                      "description": "",
                      "address": "",
                      "phone_number": "",
                      "site_url": "",
                      "site_description": null,
                      "questions": null,
                      "deleted_at": null,
                      "Rooms": null,
                      "AccomodationDesigns": null,
                      "Plans": null,
                      "Options": null,
                      "EmailSettings": null,
                      "CancelPolicies": null,
                      "AdminUsers": null,
                      "TravelerTypes": null,
                      "Reservations": null
                  },
                  "Plans": null,
                  "RoomDetails": null
              }
          },
          {
              "id": 7,
              "room_id": 1,
              "stock": 4,
              "price": 40,
              "date": "2021-10-15T00:00:00+09:00",
              "deleted_at": null,
              "Room": {
                  "id": 0,
                  "accomodation_id": 0,
                  "name": "",
                  "room_cd": "",
                  "description": "",
                  "count": 0,
                  "capacity": 0,
                  "weekday_price": 0,
                  "friday_price": 0,
                  "staurday_price": 0,
                  "before_holiday_price": 0,
                  "deleted_at": null,
                  "Accomodation": {
                      "id": 0,
                      "name": "",
                      "description": "",
                      "address": "",
                      "phone_number": "",
                      "site_url": "",
                      "site_description": null,
                      "questions": null,
                      "deleted_at": null,
                      "Rooms": null,
                      "AccomodationDesigns": null,
                      "Plans": null,
                      "Options": null,
                      "EmailSettings": null,
                      "CancelPolicies": null,
                      "AdminUsers": null,
                      "TravelerTypes": null,
                      "Reservations": null
                  },
                  "Plans": null,
                  "RoomDetails": null
              }
          }
      ]
  },
  {
      "id": 2,
      "accomodation_id": 1,
      "name": "部屋名B",
      "room_cd": "093092",
      "description": "この部屋にはたくさんの人が入る",
      "count": 6,
      "capacity": 90909,
      "weekday_price": 1000,
      "friday_price": 100000,
      "staurday_price": 203000,
      "before_holiday_price": 4007,
      "deleted_at": null,
      "Accomodation": {
          "id": 0,
          "name": "",
          "description": "",
          "address": "",
          "phone_number": "",
          "site_url": "",
          "site_description": null,
          "questions": null,
          "deleted_at": null,
          "Rooms": null,
          "AccomodationDesigns": null,
          "Plans": null,
          "Options": null,
          "EmailSettings": null,
          "CancelPolicies": null,
          "AdminUsers": null,
          "TravelerTypes": null,
          "Reservations": null
      },
      "Plans": null,
      "RoomDetails": [
          {
              "id": 3,
              "room_id": 2,
              "stock": 0,
              "price": 1000,
              "date": "2021-10-13T00:00:00+09:00",
              "deleted_at": null,
              "Room": {
                  "id": 0,
                  "accomodation_id": 0,
                  "name": "",
                  "room_cd": "",
                  "description": "",
                  "count": 0,
                  "capacity": 0,
                  "weekday_price": 0,
                  "friday_price": 0,
                  "staurday_price": 0,
                  "before_holiday_price": 0,
                  "deleted_at": null,
                  "Accomodation": {
                      "id": 0,
                      "name": "",
                      "description": "",
                      "address": "",
                      "phone_number": "",
                      "site_url": "",
                      "site_description": null,
                      "questions": null,
                      "deleted_at": null,
                      "Rooms": null,
                      "AccomodationDesigns": null,
                      "Plans": null,
                      "Options": null,
                      "EmailSettings": null,
                      "CancelPolicies": null,
                      "AdminUsers": null,
                      "TravelerTypes": null,
                      "Reservations": null
                  },
                  "Plans": null,
                  "RoomDetails": null
              }
          }
      ]
  },
  {
      "id": 3,
      "accomodation_id": 1,
      "name": "部屋名C",
      "room_cd": "9",
      "description": "9",
      "count": 10,
      "capacity": 89,
      "weekday_price": 100,
      "friday_price": 1030,
      "staurday_price": 49,
      "before_holiday_price": 89,
      "deleted_at": null,
      "Accomodation": {
          "id": 0,
          "name": "",
          "description": "",
          "address": "",
          "phone_number": "",
          "site_url": "",
          "site_description": null,
          "questions": null,
          "deleted_at": null,
          "Rooms": null,
          "AccomodationDesigns": null,
          "Plans": null,
          "Options": null,
          "EmailSettings": null,
          "CancelPolicies": null,
          "AdminUsers": null,
          "TravelerTypes": null,
          "Reservations": null
      },
      "Plans": null,
      "RoomDetails": [
          {
              "id": 5,
              "room_id": 3,
              "stock": 0,
              "price": 100,
              "date": "2021-10-13T00:00:00+09:00",
              "deleted_at": null,
              "Room": {
                  "id": 0,
                  "accomodation_id": 0,
                  "name": "",
                  "room_cd": "",
                  "description": "",
                  "count": 0,
                  "capacity": 0,
                  "weekday_price": 0,
                  "friday_price": 0,
                  "staurday_price": 0,
                  "before_holiday_price": 0,
                  "deleted_at": null,
                  "Accomodation": {
                      "id": 0,
                      "name": "",
                      "description": "",
                      "address": "",
                      "phone_number": "",
                      "site_url": "",
                      "site_description": null,
                      "questions": null,
                      "deleted_at": null,
                      "Rooms": null,
                      "AccomodationDesigns": null,
                      "Plans": null,
                      "Options": null,
                      "EmailSettings": null,
                      "CancelPolicies": null,
                      "AdminUsers": null,
                      "TravelerTypes": null,
                      "Reservations": null
                  },
                  "Plans": null,
                  "RoomDetails": null
              }
          },
          {
              "id": 6,
              "room_id": 3,
              "stock": 0,
              "price": 1030,
              "date": "2021-10-15T00:00:00+09:00",
              "deleted_at": null,
              "Room": {
                  "id": 0,
                  "accomodation_id": 0,
                  "name": "",
                  "room_cd": "",
                  "description": "",
                  "count": 0,
                  "capacity": 0,
                  "weekday_price": 0,
                  "friday_price": 0,
                  "staurday_price": 0,
                  "before_holiday_price": 0,
                  "deleted_at": null,
                  "Accomodation": {
                      "id": 0,
                      "name": "",
                      "description": "",
                      "address": "",
                      "phone_number": "",
                      "site_url": "",
                      "site_description": null,
                      "questions": null,
                      "deleted_at": null,
                      "Rooms": null,
                      "AccomodationDesigns": null,
                      "Plans": null,
                      "Options": null,
                      "EmailSettings": null,
                      "CancelPolicies": null,
                      "AdminUsers": null,
                      "TravelerTypes": null,
                      "Reservations": null
                  },
                  "Plans": null,
                  "RoomDetails": null
              }
          }
      ]
  }
]

export {data}